In [23]:
import pandas as pd

df = pd.read_csv("../data/raw/WA_Fn-UseC_-HR-Employee-Attrition.csv")

df.head()

,Age,Attrition,BusinessTravel,DailyRate,Department,DistanceFromHome,Education,EducationField,EmployeeCount,EmployeeNumber,...,RelationshipSatisfaction,StandardHours,StockOptionLevel,TotalWorkingYears,TrainingTimesLastYear,WorkLifeBalance,YearsAtCompany,YearsInCurrentRole,YearsSinceLastPromotion,YearsWithCurrManager
0,41,Yes,Travel_Rarely,1102,Sales,1,2,Life Sciences,1,1,...,1,80,0,8,0,1,6,4,0,5
1,49,No,Travel_Frequently,279,Research & Development,8,1,Life Sciences,1,2,...,4,80,1,10,3,3,10,7,1,7
2,37,Yes,Travel_Rarely,1373,Research & Development,2,2,Other,1,4,...,2,80,0,7,3,3,0,0,0,0
3,33,No,Travel_Frequently,1392,Research & Development,3,4,Life Sciences,1,5,...,3,80,0,8,3,3,8,7,3,0
4,27,No,Travel_Rarely,591,Research & Development,2,1,Medical,1,7,...,4,80,1,6,3,3,2,2,2,2

In [24]:
print(df['BusinessTravel'].unique())

<StringArray>
['Travel_Rarely', 'Travel_Frequently', 'Non-Travel']
Length: 3, dtype: str

In [25]:
#Encodes travel frequencies
#0 = Non-Traveler
#1 = Travel_Rarely
#2 = Travel_Frequently
travel_map = {
    'Non-Travel': 0,
    'Travel_Rarely': 1,
    'Travel_Frequently': 2
}
df['BusinessTravel'] = df['BusinessTravel'].map(travel_map)
print(df['BusinessTravel'].unique())
df.head()

[1 2 0]

,Age,Attrition,BusinessTravel,DailyRate,Department,DistanceFromHome,Education,EducationField,EmployeeCount,EmployeeNumber,...,RelationshipSatisfaction,StandardHours,StockOptionLevel,TotalWorkingYears,TrainingTimesLastYear,WorkLifeBalance,YearsAtCompany,YearsInCurrentRole,YearsSinceLastPromotion,YearsWithCurrManager
0,41,Yes,1,1102,Sales,1,2,Life Sciences,1,1,...,1,80,0,8,0,1,6,4,0,5
1,49,No,2,279,Research & Development,8,1,Life Sciences,1,2,...,4,80,1,10,3,3,10,7,1,7
2,37,Yes,1,1373,Research & Development,2,2,Other,1,4,...,2,80,0,7,3,3,0,0,0,0
3,33,No,2,1392,Research & Development,3,4,Life Sciences,1,5,...,3,80,0,8,3,3,8,7,3,0
4,27,No,1,591,Research & Development,2,1,Medical,1,7,...,4,80,1,6,3,3,2,2,2,2

In [26]:
yn_map = {
    'No': 0,
    'Yes': 1
}
df['Attrition'] = df['Attrition'].map(yn_map)
print(df['Attrition'].unique())
df.head()

[1 0]

,Age,Attrition,BusinessTravel,DailyRate,Department,DistanceFromHome,Education,EducationField,EmployeeCount,EmployeeNumber,...,RelationshipSatisfaction,StandardHours,StockOptionLevel,TotalWorkingYears,TrainingTimesLastYear,WorkLifeBalance,YearsAtCompany,YearsInCurrentRole,YearsSinceLastPromotion,YearsWithCurrManager
0,41,1,1,1102,Sales,1,2,Life Sciences,1,1,...,1,80,0,8,0,1,6,4,0,5
1,49,0,2,279,Research & Development,8,1,Life Sciences,1,2,...,4,80,1,10,3,3,10,7,1,7
2,37,1,1,1373,Research & Development,2,2,Other,1,4,...,2,80,0,7,3,3,0,0,0,0
3,33,0,2,1392,Research & Development,3,4,Life Sciences,1,5,...,3,80,0,8,3,3,8,7,3,0
4,27,0,1,591,Research & Development,2,1,Medical,1,7,...,4,80,1,6,3,3,2,2,2,2

In [28]:
df['OverTime'] = df['OverTime'].map(yn_map)
print(df['OverTime'].unique())
df.head()

[1 0]

,Age,Attrition,BusinessTravel,DailyRate,Department,DistanceFromHome,Education,EducationField,EmployeeNumber,EnvironmentSatisfaction,...,PerformanceRating,RelationshipSatisfaction,StockOptionLevel,TotalWorkingYears,TrainingTimesLastYear,WorkLifeBalance,YearsAtCompany,YearsInCurrentRole,YearsSinceLastPromotion,YearsWithCurrManager
0,41,1,1,1102,Sales,1,2,Life Sciences,1,2,...,3,1,0,8,0,1,6,4,0,5
1,49,0,2,279,Research & Development,8,1,Life Sciences,2,3,...,4,4,1,10,3,3,10,7,1,7
2,37,1,1,1373,Research & Development,2,2,Other,4,4,...,3,2,0,7,3,3,0,0,0,0
3,33,0,2,1392,Research & Development,3,4,Life Sciences,5,4,...,3,3,0,8,3,3,8,7,3,0
4,27,0,1,591,Research & Development,2,1,Medical,7,1,...,3,4,1,6,3,3,2,2,2,2

In [29]:
df = pd.get_dummies(df, columns=['Gender'], dtype=int)
df.head()

,Age,Attrition,BusinessTravel,DailyRate,Department,DistanceFromHome,Education,EducationField,EmployeeNumber,EnvironmentSatisfaction,...,StockOptionLevel,TotalWorkingYears,TrainingTimesLastYear,WorkLifeBalance,YearsAtCompany,YearsInCurrentRole,YearsSinceLastPromotion,YearsWithCurrManager,Gender_Female,Gender_Male
0,41,1,1,1102,Sales,1,2,Life Sciences,1,2,...,0,8,0,1,6,4,0,5,1,0
1,49,0,2,279,Research & Development,8,1,Life Sciences,2,3,...,1,10,3,3,10,7,1,7,0,1
2,37,1,1,1373,Research & Development,2,2,Other,4,4,...,0,7,3,3,0,0,0,0,0,1
3,33,0,2,1392,Research & Development,3,4,Life Sciences,5,4,...,0,8,3,3,8,7,3,0,1,0
4,27,0,1,591,Research & Development,2,1,Medical,7,1,...,1,6,3,3,2,2,2,2,0,1

In [31]:
#Removed columns that had no predictive variablity (i.e. only one unique value)
df_summary = pd.DataFrame({
    'Data Type': df.dtypes,
    'Unique': df.nunique()
})
df_summary

                         Data Type  Unique
Age                          int64      43
Attrition                    int64       2
BusinessTravel               int64       3
DailyRate                    int64     886
Department                     str       3
DistanceFromHome             int64      29
Education                    int64       5
EducationField                 str       6
EmployeeNumber               int64    1470
EnvironmentSatisfaction      int64       4
HourlyRate                   int64      71
JobInvolvement               int64       4
JobLevel                     int64       5
JobRole                        str       9
JobSatisfaction              int64       4
MaritalStatus                  str       3
MonthlyIncome                int64    1349
MonthlyRate                  int64    1427
NumCompaniesWorked           int64      10
OverTime                     int64       2
PercentSalaryHike            int64      15
PerformanceRating            int64       2
RelationshipSatisfaction     int64       4
StockOptionLevel             int64       4
TotalWorkingYears            int64      40
TrainingTimesLastYear        int64       7
WorkLifeBalance              int64       4
YearsAtCompany               int64      37
YearsInCurrentRole           int64      19
YearsSinceLastPromotion      int64      16
YearsWithCurrManager         int64      18
Gender_Female                int64       2
Gender_Male                  int64       2