In [29]:
%pip install pandas
import pandas as pd

Requirement already satisfied: pandas in c:\Users\11yun\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (3.0.5)
Requirement already satisfied: numpy>=2.3.3 in c:\Users\11yun\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from pandas) (2.5.2)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\Users\11yun\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: tzdata in c:\Users\11yun\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from pandas) (2026.3)
Requirement already satisfied: six>=1.5 in c:\Users\11yun\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Note: you may need to restart the kernel to use updated packages.

In [30]:

# Loading our attrition data into a pandas dataframe
df = pd.read_csv(
    "../data/raw/WA_Fn-UseC_-HR-Employee-Attrition.csv"
)

In [31]:
# Attrition rate by each useful column
# AttritionRate is the share of employees in each group who left.

# Make a new column AttritionFlag that is True (1) for employees who left and False (0) for those who stayed.
df["AttritionFlag"] = df["Attrition"].eq("Yes")

# Compute the overall attrition rate to use as a baseline for comparison.
baseline_rate = df["AttritionFlag"].mean()
print(f"Overall attrition rate: {baseline_rate:.1%}")

# Identify columns that are not useful for attrition analysis.
constant_columns = [
    column for column in df.columns
    if df[column].nunique(dropna=False) <= 1
]
identifier_columns = ["EmployeeNumber"]
exclude_columns = {"Attrition", "AttritionFlag", *constant_columns, *identifier_columns}

# Group attrition rates by each useful column, and compare to the overall baseline rate.
results = []
for column in df.columns:
    # Skip columns that are not useful for attrition analysis.
    if column in exclude_columns:
        continue
    grouped_data = df[[column, "AttritionFlag"]].copy()
    group_column = column
    # If the column is numeric, create quartile bands to group the data.
    if pd.api.types.is_numeric_dtype(grouped_data[column]):
        group_column = f"{column}Band"
        grouped_data[group_column] = pd.qcut(
            grouped_data[column],
            q=4,
            duplicates="drop"
        )
    # Compute the attrition rate for each group and compare to the baseline.
    grouped_rates = (
        grouped_data
        .groupby(group_column, observed=False)["AttritionFlag"]
        .agg(
            Employees="size",
            Leavers="sum",
            AttritionRate="mean"
        )
        .reset_index()
    )

    # Add the column name to the results so we can identify which feature each group belongs to.
    grouped_rates.insert(0, "Feature", column)
    grouped_rates["RateVsBaseline"] = grouped_rates["AttritionRate"] - baseline_rate
    results.append(grouped_rates)

attrition_by_group = pd.concat(results, ignore_index=True)
# Format the attrition rates as percentages for easier reading.
attrition_by_group["AttritionRate"] = attrition_by_group["AttritionRate"].map(
    lambda rate: f"{rate:.1%}"
)
# Format the difference from baseline as a percentage with a sign to indicate whether the group is above or below the baseline.
attrition_by_group["RateVsBaseline"] = attrition_by_group["RateVsBaseline"].map(
    lambda rate: f"{rate:+.1%}"
)

# Sort the largest groups first so small, unstable groups do not dominate the view.
attrition_by_group = attrition_by_group.sort_values(
    ["Feature", "Employees"],
    ascending=[True, False]
)

# Pearson correlation with the binary AttritionFlag is a quick numeric screening tool.
numeric_columns = [
    column for column in df.select_dtypes(include="number").columns
    if column not in exclude_columns
]
# Compute the correlation of each numeric column with AttritionFlag, and sort by absolute value.
attrition_correlations = (
    df[numeric_columns]
    .corrwith(df["AttritionFlag"])
    .sort_values(key=lambda values: values.abs(), ascending=False)
    .rename("CorrelationWithAttrition")
    .to_frame()
)

print("\nGrouped attrition rates:")
display(attrition_by_group.head(30))
print("\nNumeric correlations with AttritionFlag:")
display(attrition_correlations)

Overall attrition rate: 16.1%

Grouped attrition rates:

,Feature,AgeBand,Employees,Leavers,AttritionRate,RateVsBaseline,BusinessTravel,DailyRateBand,Department,DistanceFromHomeBand,...,PerformanceRatingBand,RelationshipSatisfactionBand,StockOptionLevelBand,TotalWorkingYearsBand,TrainingTimesLastYearBand,WorkLifeBalanceBand,YearsAtCompanyBand,YearsInCurrentRoleBand,YearsSinceLastPromotionBand,YearsWithCurrManagerBand
1,Age,"(30.0, 36.0]",412,66,16.0%,-0.1%,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
0,Age,"(17.999, 30.0]",386,100,25.9%,+9.8%,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,Age,"(43.0, 60.0]",347,42,12.1%,-4.0%,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Age,"(36.0, 43.0]",325,29,8.9%,-7.2%,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,BusinessTravel,NaN,1043,156,15.0%,-1.2%,Travel_Rarely,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,BusinessTravel,NaN,277,69,24.9%,+8.8%,Travel_Frequently,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,BusinessTravel,NaN,150,12,8.0%,-8.1%,Non-Travel,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,DailyRate,NaN,369,74,20.1%,+3.9%,NaN,"(101.999, 465.0]",NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,DailyRate,NaN,367,59,16.1%,-0.0%,NaN,"(465.0, 802.0]",NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,DailyRate,NaN,367,56,15.3%,-0.9%,NaN,"(802.0, 1157.0]",NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10,DailyRate,NaN,367,48,13.1%,-3.0%,NaN,"(1157.0, 1499.0]",NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12,Department,NaN,961,133,13.8%,-2.3%,NaN,NaN,Research & Development,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
13,Department,NaN,446,92,20.6%,+4.5%,NaN,NaN,Sales,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
11,Department,NaN,63,12,19.0%,+2.9%,NaN,NaN,Human Resources,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
14,DistanceFromHome,NaN,419,54,12.9%,-3.2%,NaN,NaN,NaN,"(0.999, 2.0]",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
15,DistanceFromHome,NaN,356,51,14.3%,-1.8%,NaN,NaN,NaN,"(2.0, 7.0]",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
17,DistanceFromHome,NaN,355,73,20.6%,+4.4%,NaN,NaN,NaN,"(14.0, 29.0]",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
16,DistanceFromHome,NaN,340,59,17.4%,+1.2%,NaN,NaN,NaN,"(7.0, 14.0]",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
19,Education,NaN,572,99,17.3%,+1.2%,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
18,Education,NaN,452,75,16.6%,+0.5%,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
20,Education,NaN,398,58,14.6%,-1.5%,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
21,Education,NaN,48,5,10.4%,-5.7%,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
23,EducationField,NaN,606,89,14.7%,-1.4%,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25,EducationField,NaN,464,63,13.6%,-2.5%,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
24,EducationField,NaN,159,35,22.0%,+5.9%,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
27,EducationField,NaN,132,32,24.2%,+8.1%,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
26,EducationField,NaN,82,11,13.4%,-2.7%,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
22,EducationField,NaN,27,7,25.9%,+9.8%,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
28,EnvironmentSatisfaction,NaN,571,115,20.1%,+4.0%,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
29,EnvironmentSatisfaction,NaN,453,62,13.7%,-2.4%,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

Numeric correlations with AttritionFlag:

                          CorrelationWithAttrition
TotalWorkingYears                        -0.171063
JobLevel                                 -0.169105
YearsInCurrentRole                       -0.160545
MonthlyIncome                            -0.159840
Age                                      -0.159205
YearsWithCurrManager                     -0.156199
StockOptionLevel                         -0.137145
YearsAtCompany                           -0.134392
JobInvolvement                           -0.130016
JobSatisfaction                          -0.103481
EnvironmentSatisfaction                  -0.103369
DistanceFromHome                          0.077924
WorkLifeBalance                          -0.063939
TrainingTimesLastYear                    -0.059478
DailyRate                                -0.056652
RelationshipSatisfaction                 -0.045872
NumCompaniesWorked                        0.043494
YearsSinceLastPromotion                  -0.033019
Education                                -0.031373
MonthlyRate                               0.015170
PercentSalaryHike                        -0.013478
HourlyRate                               -0.006846
PerformanceRating                         0.002889

In [32]:
# Compute the correlation of each numeric column with AttritionFlag, and sort by absolute value.
correlation_data = df[numeric_columns].copy()
correlation_data["AttritionFlag"] = df["AttritionFlag"].astype(int)

correlation_data.corr()["AttritionFlag"].sort_values(key=lambda values: values.abs(), ascending=False)

AttritionFlag               1.000000
TotalWorkingYears          -0.171063
JobLevel                   -0.169105
YearsInCurrentRole         -0.160545
MonthlyIncome              -0.159840
Age                        -0.159205
YearsWithCurrManager       -0.156199
StockOptionLevel           -0.137145
YearsAtCompany             -0.134392
JobInvolvement             -0.130016
JobSatisfaction            -0.103481
EnvironmentSatisfaction    -0.103369
DistanceFromHome            0.077924
WorkLifeBalance            -0.063939
TrainingTimesLastYear      -0.059478
DailyRate                  -0.056652
RelationshipSatisfaction   -0.045872
NumCompaniesWorked          0.043494
YearsSinceLastPromotion    -0.033019
Education                  -0.031373
MonthlyRate                 0.015170
PercentSalaryHike          -0.013478
HourlyRate                 -0.006846
PerformanceRating           0.002889
Name: AttritionFlag, dtype: float64

In [ ]:
# Create one grouped correlation DataFrame for every analyzed feature.
attrition_correlations_by_group = {}

for feature in attrition_correlations.index:
    feature_data = df[[feature, "AttritionFlag"]].copy()

    if pd.api.types.is_numeric_dtype(feature_data[feature]):
        feature_data["Group"] = pd.qcut(
            feature_data[feature],
            q=4,
            duplicates="drop"
        )
    else:
        feature_data["Group"] = feature_data[feature].fillna("Missing")

    group_rows = []
    for group_value, group in feature_data.groupby(
        "Group",
        observed=False,
        sort=False
    ):
        group_membership = feature_data["Group"].eq(group_value).astype(int)
        group_rows.append({
            "Feature": feature,
            "Group": group_value,
            "Employees": len(group),
            "Leavers": int(group["AttritionFlag"].sum()),
            "AttritionRate": group["AttritionFlag"].mean(),
            "RateVsBaseline": group["AttritionFlag"].mean() - baseline_rate,
            "GroupAttritionCorrelation": group_membership.corr(
                feature_data["AttritionFlag"].astype(int)
            ),
        })

    attrition_correlations_by_group[feature] = pd.DataFrame(group_rows)

In [ ]:
for feature, correlation_df in attrition_correlations_by_group.items():
    print(f"\n{feature}")
    sorted_correlation_df = correlation_df.sort_values(
        "Group",
        ascending=True
    ).reset_index(drop=True).copy()
    sorted_correlation_df["AttritionRate"] = sorted_correlation_df[
        "AttritionRate"
    ].map(lambda rate: f"{rate:.1%}")
    sorted_correlation_df["RateVsBaseline"] = sorted_correlation_df[
        "RateVsBaseline"
    ].map(lambda rate: f"{rate:+.1%}")
    display(sorted_correlation_df)

TotalWorkingYears

,Feature,Group,Employees,Leavers,AttritionRate,RateVsBaseline,GroupAttritionCorrelation
0,TotalWorkingYears,"(-0.001, 6.0]",441,113,0.256236,0.095011,0.169141
1,TotalWorkingYears,"(6.0, 10.0]",482,69,0.143154,-0.018071,-0.034323
2,TotalWorkingYears,"(10.0, 15.0]",191,24,0.125654,-0.035570,-0.037379
3,TotalWorkingYears,"(15.0, 40.0]",356,31,0.087079,-0.074146,-0.113981

JobLevel

,Feature,Group,Employees,Leavers,AttritionRate,RateVsBaseline,GroupAttritionCorrelation
0,JobLevel,"(0.999, 2.0]",1077,195,0.181058,0.019834,0.089286
1,JobLevel,"(2.0, 3.0]",218,32,0.146789,-0.014435,-0.016380
2,JobLevel,"(3.0, 5.0]",175,10,0.057143,-0.104082,-0.104045

YearsInCurrentRole

,Feature,Group,Employees,Leavers,AttritionRate,RateVsBaseline,GroupAttritionCorrelation
0,YearsInCurrentRole,"(-0.001, 2.0]",673,152,0.225854,0.064630,0.161500
1,YearsInCurrentRole,"(2.0, 3.0]",135,16,0.118519,-0.042706,-0.036930
2,YearsInCurrentRole,"(3.0, 7.0]",399,49,0.122807,-0.038417,-0.063765
3,YearsInCurrentRole,"(7.0, 18.0]",263,20,0.076046,-0.085179,-0.108123

MonthlyIncome

,Feature,Group,Employees,Leavers,AttritionRate,RateVsBaseline,GroupAttritionCorrelation
0,MonthlyIncome,"(1008.999, 2911.0]",369,108,0.292683,0.131458,0.206952
1,MonthlyIncome,"(2911.0, 4919.0]",366,52,0.142077,-0.019148,-0.029981
2,MonthlyIncome,"(4919.0, 8379.0]",367,39,0.106267,-0.054957,-0.086205
3,MonthlyIncome,"(8379.0, 19999.0]",368,38,0.103261,-0.057964,-0.091086

Age

,Feature,Group,Employees,Leavers,AttritionRate,RateVsBaseline,GroupAttritionCorrelation
0,Age,"(17.999, 30.0]",386,100,0.259067,0.097843,0.158770
1,Age,"(30.0, 36.0]",412,66,0.160194,-0.001030,-0.001748
2,Age,"(36.0, 43.0]",325,29,0.089231,-0.071994,-0.104303
3,Age,"(43.0, 60.0]",347,42,0.121037,-0.040187,-0.060747

YearsWithCurrManager

,Feature,Group,Employees,Leavers,AttritionRate,RateVsBaseline,GroupAttritionCorrelation
0,YearsWithCurrManager,"(-0.001, 2.0]",683,146,0.213763,0.052538,0.133095
1,YearsWithCurrManager,"(2.0, 3.0]",142,19,0.133803,-0.027422,-0.024384
2,YearsWithCurrManager,"(3.0, 7.0]",374,50,0.133690,-0.027535,-0.043739
3,YearsWithCurrManager,"(7.0, 17.0]",271,22,0.081181,-0.080044,-0.103482

StockOptionLevel

,Feature,Group,Employees,Leavers,AttritionRate,RateVsBaseline,GroupAttritionCorrelation
0,StockOptionLevel,"(-0.001, 1.0]",1227,210,0.171149,0.009925,0.060645
1,StockOptionLevel,"(1.0, 3.0]",243,27,0.111111,-0.050113,-0.060645

YearsAtCompany

,Feature,Group,Employees,Leavers,AttritionRate,RateVsBaseline,GroupAttritionCorrelation
0,YearsAtCompany,"(-0.001, 3.0]",470,122,0.259574,0.098350,0.183352
1,YearsAtCompany,"(3.0, 5.0]",306,40,0.130719,-0.030506,-0.042533
2,YearsAtCompany,"(5.0, 9.0]",328,37,0.112805,-0.048420,-0.070565
3,YearsAtCompany,"(9.0, 40.0]",366,38,0.103825,-0.057399,-0.089872

JobInvolvement

,Feature,Group,Employees,Leavers,AttritionRate,RateVsBaseline,GroupAttritionCorrelation
0,JobInvolvement,"(0.999, 2.0]",458,99,0.216157,0.054933,0.100493
1,JobInvolvement,"(2.0, 3.0]",868,125,0.144009,-0.017215,-0.056213
2,JobInvolvement,"(3.0, 4.0]",144,13,0.090278,-0.070947,-0.063577

JobSatisfaction

,Feature,Group,Employees,Leavers,AttritionRate,RateVsBaseline,GroupAttritionCorrelation
0,JobSatisfaction,"(0.999, 2.0]",569,112,0.196837,0.035612,0.076958
1,JobSatisfaction,"(2.0, 3.0]",442,73,0.165158,0.003934,0.007015
2,JobSatisfaction,"(3.0, 4.0]",459,52,0.113290,-0.047935,-0.087830

EnvironmentSatisfaction

,Feature,Group,Employees,Leavers,AttritionRate,RateVsBaseline,GroupAttritionCorrelation
0,EnvironmentSatisfaction,"(0.999, 2.0]",571,115,0.201401,0.040177,0.087071
1,EnvironmentSatisfaction,"(2.0, 3.0]",453,62,0.136865,-0.024359,-0.044209
2,EnvironmentSatisfaction,"(3.0, 4.0]",446,60,0.134529,-0.026695,-0.047909

DistanceFromHome

,Feature,Group,Employees,Leavers,AttritionRate,RateVsBaseline,GroupAttritionCorrelation
0,DistanceFromHome,"(0.999, 2.0]",419,54,0.128878,-0.032346,-0.055538
1,DistanceFromHome,"(2.0, 7.0]",356,51,0.143258,-0.017966,-0.027618
2,DistanceFromHome,"(7.0, 14.0]",340,59,0.173529,0.012305,0.018354
3,DistanceFromHome,"(14.0, 29.0]",355,73,0.205634,0.044409,0.068142

WorkLifeBalance

,Feature,Group,Employees,Leavers,AttritionRate,RateVsBaseline,GroupAttritionCorrelation
0,WorkLifeBalance,"(0.999, 2.0]",424,83,0.195755,0.034530,0.059783
1,WorkLifeBalance,"(2.0, 3.0]",893,127,0.142217,-0.019007,-0.064301
2,WorkLifeBalance,"(3.0, 4.0]",153,27,0.176471,0.015246,0.014131

TrainingTimesLastYear

,Feature,Group,Employees,Leavers,AttritionRate,RateVsBaseline,GroupAttritionCorrelation
0,TrainingTimesLastYear,"(-0.001, 2.0]",672,122,0.181548,0.020323,0.050715
1,TrainingTimesLastYear,"(2.0, 3.0]",491,69,0.140530,-0.020695,-0.039854
2,TrainingTimesLastYear,"(3.0, 6.0]",307,46,0.149837,-0.011387,-0.015910

DailyRate

,Feature,Group,Employees,Leavers,AttritionRate,RateVsBaseline,GroupAttritionCorrelation
0,DailyRate,"(101.999, 465.0]",369,74,0.200542,0.039318,0.061897
1,DailyRate,"(465.0, 802.0]",367,59,0.160763,-0.000462,-0.000724
2,DailyRate,"(802.0, 1157.0]",367,56,0.152589,-0.008636,-0.013546
3,DailyRate,"(1157.0, 1499.0]",367,48,0.130790,-0.030434,-0.047739

RelationshipSatisfaction

,Feature,Group,Employees,Leavers,AttritionRate,RateVsBaseline,GroupAttritionCorrelation
0,RelationshipSatisfaction,"(0.999, 2.0]",579,102,0.176166,0.014941,0.032753
1,RelationshipSatisfaction,"(2.0, 3.0]",459,71,0.154684,-0.006540,-0.011984
2,RelationshipSatisfaction,"(3.0, 4.0]",432,64,0.148148,-0.013076,-0.022940

NumCompaniesWorked

,Feature,Group,Employees,Leavers,AttritionRate,RateVsBaseline,GroupAttritionCorrelation
0,NumCompaniesWorked,"(-0.001, 1.0]",718,121,0.168524,0.007299,0.019395
1,NumCompaniesWorked,"(1.0, 2.0]",146,16,0.109589,-0.051635,-0.046627
2,NumCompaniesWorked,"(2.0, 4.0]",298,33,0.110738,-0.050486,-0.069228
3,NumCompaniesWorked,"(4.0, 9.0]",308,67,0.217532,0.056308,0.078832

YearsSinceLastPromotion

,Feature,Group,Employees,Leavers,AttritionRate,RateVsBaseline,GroupAttritionCorrelation
0,YearsSinceLastPromotion,"(-0.001, 1.0]",938,159,0.169510,0.008285,0.029916
1,YearsSinceLastPromotion,"(1.0, 3.0]",211,36,0.170616,0.009392,0.010455
2,YearsSinceLastPromotion,"(3.0, 15.0]",321,42,0.130841,-0.030383,-0.043671

Education

,Feature,Group,Employees,Leavers,AttritionRate,RateVsBaseline,GroupAttritionCorrelation
0,Education,"(0.999, 2.0]",452,75,0.165929,0.004705,0.008525
1,Education,"(2.0, 3.0]",572,99,0.173077,0.011852,0.025723
2,Education,"(3.0, 4.0]",398,58,0.145729,-0.015496,-0.025676
3,Education,"(4.0, 5.0]",48,5,0.104167,-0.057058,-0.028507

MonthlyRate

,Feature,Group,Employees,Leavers,AttritionRate,RateVsBaseline,GroupAttritionCorrelation
0,MonthlyRate,"(2093.999, 8047.0]",368,53,0.144022,-0.017203,-0.027033
1,MonthlyRate,"(8047.0, 14235.5]",367,61,0.166213,0.004988,0.007824
2,MonthlyRate,"(14235.5, 20461.5]",367,57,0.155313,-0.005911,-0.009272
3,MonthlyRate,"(20461.5, 26999.0]",368,66,0.179348,0.018123,0.028480

PercentSalaryHike

,Feature,Group,Employees,Leavers,AttritionRate,RateVsBaseline,GroupAttritionCorrelation
0,PercentSalaryHike,"(10.999, 12.0]",408,74,0.181373,0.020148,0.033960
1,PercentSalaryHike,"(12.0, 14.0]",410,58,0.141463,-0.019761,-0.033420
2,PercentSalaryHike,"(14.0, 18.0]",350,59,0.168571,0.007347,0.011168
3,PercentSalaryHike,"(18.0, 25.0]",302,46,0.152318,-0.008907,-0.012316

HourlyRate

,Feature,Group,Employees,Leavers,AttritionRate,RateVsBaseline,GroupAttritionCorrelation
0,HourlyRate,"(29.999, 48.0]",375,57,0.152000,-0.009224,-0.014680
1,HourlyRate,"(48.0, 66.0]",378,68,0.179894,0.018670,0.029870
2,HourlyRate,"(66.0, 83.75]",349,51,0.146132,-0.015093,-0.022900
3,HourlyRate,"(83.75, 100.0]",368,61,0.165761,0.004536,0.007129

PerformanceRating

,Feature,Group,Employees,Leavers,AttritionRate,RateVsBaseline,GroupAttritionCorrelation
0,PerformanceRating,"(2.999, 4.0]",1470,237,0.161224,0.0,NaN